branches:
  only:
  - master

language: node_js
node_js:
  - "8"
cache:
  npm: true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true

install:
  - npm install

script:
  - SOLIDITY_COVERAGE=true npm run test

deploy:
  provider: script
  script:
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
    - GIT_USER="${GH_NAME}" npm run docs-publish
  on:
    branch: master

